// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM0uMC6gJDiLPmWjcc00iTjOt38eFAJLE',
    appId: '1:215226798593:web:d4521b67bfed98e7f2a600',
    messagingSenderId: '215226798593',
    projectId: 'deliveryappnew-15dfb',
    authDomain: 'deliveryappnew-15dfb.firebaseapp.com',
    storageBucket: 'deliveryappnew-15dfb.appspot.com',
    measurementId: 'G-7SQ5353PN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Cb-4A3q_V0ZrRLwRddw_cjLHvDf0ElU',
    appId: '1:215226798593:android:4ea7479d34118089f2a600',
    messagingSenderId: '215226798593',
    projectId: 'deliveryappnew-15dfb',
    storageBucket: 'deliveryappnew-15dfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9xbYpH1toiXFPN9pHfQZdu2SKqHCvcFQ',
    appId: '1:215226798593:ios:1eea37ca22758094f2a600',
    messagingSenderId: '215226798593',
    projectId: 'deliveryappnew-15dfb',
    storageBucket: 'deliveryappnew-15dfb.appspot.com',
    iosBundleId: 'Majdi.com.sellerAppDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9xbYpH1toiXFPN9pHfQZdu2SKqHCvcFQ',
    appId: '1:215226798593:ios:1eea37ca22758094f2a600',
    messagingSenderId: '215226798593',
    projectId: 'deliveryappnew-15dfb',
    storageBucket: 'deliveryappnew-15dfb.appspot.com',
    iosBundleId: 'Majdi.com.sellerAppDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM0uMC6gJDiLPmWjcc00iTjOt38eFAJLE',
    appId: '1:215226798593:web:1beec1d2ef9a33dbf2a600',
    messagingSenderId: '215226798593',
    projectId: 'deliveryappnew-15dfb',
    authDomain: 'deliveryappnew-15dfb.firebaseapp.com',
    storageBucket: 'deliveryappnew-15dfb.appspot.com',
    measurementId: 'G-HVFMEW4G9K',
  );
}
